### ISSUE TITLE
how to disable SSL

### ISSUE THREAD

**Issue by mannigit** [yabacon/paystack-class#2]
I am using on XAMP installed in local machine. I want to disable the SSL either via library function or any how.

I am getting below error.

Fatal error: Uncaught exception 'Exception' with message 'Curl failed with response: 'SSL certificate problem: unable to get local issuer certificate'.' in C:\xampp\htdocs\PHPCodes\Test\social\includes\paystack\Paystack.php:701 Stack trace: #0 C:\xampp\htdocs\PHPCodes\Test\social\includes\paystack\Paystack.php(358): PaystackHttpResponse->wrapUp() #1 C:\xampp\htdocs\PHPCodes\Test\social\includes\paystack\Paystack.php(436): PaystackHelpersCaller->callEndpoint(Array, Array, Array) #2 [internal function]: PaystackHelpersRouter->{closure}(Array) #3 C:\xampp\htdocs\PHPCodes\Test\social\includes\paystack\Paystack.php(391): call_user_func_array(Object(Closure), Array) #4 C:\xampp\htdocs\PHPCodes\Test\social\includes\verify.php(37): PaystackHelpersRouter->__call('verify', Array) #5 C:\xampp\htdocs\PHPCodes\Test\social\includes\verify.php(37): PaystackHelpersRouter->verify(Array) #6 {main} thrown in C:\xampp\htdocs\PHPCodes\Test\social\includes\paystack\Paystack.php on line 701

used the solution
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);

from https://developers.paystack.co/discuss/58fa2b1616c90d2f0087be27

but not working.

**Comment by ibrahimlawal** [comment]
Don't disable SSL. This is payments.

Try this instead.

https://github.com/yabacon/paystack-php/wiki/cURL-error-60:-SSL-certificate-problem:-unable-to-get-local-issuer-certificate-(see-http:--curl.haxx.se-libcurl-c-libcurl-errors.html)

**Comment by mannigit** [comment]
Hi Ibrahim,

It worked very well. Thank you very much.

*Best Regards,*
*Manish.*
*+91-8770548457*

**Comment by ibrahimlawal** [comment]
Glad to be of assistance
